// Target-scoped suppressions for warnings on non-editable generated/SDK code only.

using System.Diagnostics.CodeAnalysis;

// SDK-provided <auto-generated> initializer (UndockedRegFreeWinRT-AutoInitializer.cs); its
// copyright header defeats Roslyn's generated-code detection, so CA5392 leaks.
[assembly: SuppressMessage(
    "Security",
    "CA5392:Use DefaultDllImportSearchPaths attribute for P/Invokes",
    Justification = "編集不可能な Windows App SDK 提供の <auto-generated> 初期化コード。生成コード相当のため対象限定で抑制。",
    Scope = "member",
    Target = "~M:Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.NativeMethods.WindowsAppRuntime_EnsureIsLoaded~System.Int32")]
