// Target-scoped suppressions for warnings on non-editable generated/SDK code only.

using System.Diagnostics.CodeAnalysis;

// SDK-provided <auto-generated> initializer (UndockedRegFreeWinRT-AutoInitializer.cs); its
// copyright header defeats Roslyn's generated-code detection, so CA5392 leaks.
[assembly: SuppressMessage(
    "Security",
    "CA5392:Use DefaultDllImportSearchPaths attribute for P/Invokes",
    Justification = "Non-editable Windows App SDK <auto-generated> initializer; effectively generated code.",
    Scope = "member",
    Target = "~M:Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.NativeMethods.WindowsAppRuntime_EnsureIsLoaded~System.Int32")]
