// Targeted suppressions for warnings originating in non-editable generated / SDK-provided code.

using System.Diagnostics.CodeAnalysis;

// The Windows App SDK injects an <auto-generated> initializer (UndockedRegFreeWinRT-AutoInitializer.cs from
// Microsoft.WindowsAppSDK.Foundation) into every project that references it. Its first line is a copyright
// notice, so Roslyn does not classify it as generated and CA5392 leaks through. The P/Invoke only calls the
// SDK's own loader (Microsoft.WindowsAppRuntime.dll) and the file is marked "DO NOT MODIFY", so it is
// suppressed for that single target.
[assembly: SuppressMessage(
    "Security",
    "CA5392:Use DefaultDllImportSearchPaths attribute for P/Invokes",
    Justification = "Non-editable Windows App SDK <auto-generated> initializer; effectively generated code.",
    Scope = "member",
    Target = "~M:Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.NativeMethods.WindowsAppRuntime_EnsureIsLoaded~System.Int32")]
